In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Student-Performance.csv')
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [3]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [5]:
df.isnull().sum() #checking for null values

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [6]:
df.dtypes

Hours Studied                         int64
Previous Scores                       int64
Extracurricular Activities           object
Sleep Hours                           int64
Sample Question Papers Practiced      int64
Performance Index                   float64
dtype: object

In [7]:
df['Extracurricular Activities'].value_counts()

Extracurricular Activities
No     5052
Yes    4948
Name: count, dtype: int64

In [8]:
df1 = df

In [ ]:
from sklearn.preprocessing import LabelEncoder, StandardScaler

#label encoder - to change the values in the extracurricular activities
# column
# so instead of yes and no - we can make it as 1 and 0
# this is one of the way to change the value to int

In [ ]:
le = LabelEncoder()

array([1, 0, 1, ..., 1, 1, 0], shape=(10000,))

In [ ]:
df['Extracurricular Activities'] = le.fit_transform(df['Extracurricular Activities'])

In [12]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,1,9,1,91.0
1,4,82,0,4,2,65.0
2,8,51,1,7,2,45.0
3,5,52,1,5,2,36.0
4,7,75,0,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,1,4,2,23.0
9996,7,64,1,8,5,58.0
9997,6,83,1,8,5,74.0
9998,9,97,1,7,0,95.0
9999,7,74,0,8,1,64.0

In [13]:
x = df[['Hours Studied', 'Previous Scores', 'Extracurricular Activities', 'Sleep Hours', 'Sample Question Papers Practiced']]
x

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,1,9,1
1,4,82,0,4,2
2,8,51,1,7,2
3,5,52,1,5,2
4,7,75,0,8,5
...,...,...,...,...,...
9995,1,49,1,4,2
9996,7,64,1,8,5
9997,6,83,1,8,5
9998,9,97,1,7,0
9999,7,74,0,8,1

In [14]:
y = df['Performance Index']
y

0       91.0
1       65.0
2       45.0
3       36.0
4       66.0
        ...
9995    23.0
9996    58.0
9997    74.0
9998    95.0
9999    64.0
Name: Performance Index, Length: 10000, dtype: float64

In [15]:
from sklearn.model_selection import train_test_split

In [16]:
xtrain, xtest, ytrain, ytest = train_test_split(x, y, test_size = 0.1)

In [17]:
xtrain

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
6701,7,64,0,8,7
5640,3,69,0,6,2
9319,3,77,0,6,3
797,1,67,1,7,1
9148,5,99,1,9,3
...,...,...,...,...,...
7823,1,74,1,8,0
1410,9,86,1,9,8
9771,5,56,1,4,9
4136,5,75,1,5,8
3034,9,54,1,4,4

In [18]:
ytest

6759    43.0
9169    62.0
2001    63.0
9042    66.0
1827    51.0
        ...
9801    36.0
8732    19.0
261     28.0
355     57.0
5608    44.0
Name: Performance Index, Length: 1000, dtype: float64

In [19]:
scaler = StandardScaler()
xtrain = scaler.fit_transform(xtrain)
xtest = scaler.fit_transform(xtest)

In [20]:
from sklearn.linear_model import LinearRegression
import pickle
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error

In [21]:
lr = LinearRegression()

In [22]:
lr.fit(xtrain, ytrain)

LinearRegression()

In [23]:
ypred = lr.predict(xtest)
ypred

array([45.9378016 , 63.35822313, 65.10025841, 66.04426141, 53.26938967,
       76.68559709, 23.35863216, 19.86913734, 28.54772295, 28.73516648,
       54.1255935 , 83.39797022, 56.82469153, 54.13129785, 55.97303241,
       54.12783543, 41.48513792, 78.61028185, 30.40731131, 60.0778839 ,
       61.779072  , 62.18144093, 34.9005362 , 71.04239133, 72.69119724,
       56.04933785, 67.24946128, 57.30560784, 53.3434839 , 40.72511603,
       43.03107273, 74.39457233, 53.94612636, 85.035573  , 46.77708151,
       45.86850603, 51.6084585 , 86.6121674 , 46.73486735, 37.67696112,
       44.85940663, 56.67872079, 81.24425928, 51.05214834, 73.50263017,
       47.31709927, 67.87282507, 31.343618  , 84.64660474, 37.31255225,
       67.79172096, 82.10040227, 53.72924372, 29.19632206, 32.46609743,
       61.46357236, 47.26789943, 67.22745862, 42.19860366, 55.23213973,
       25.55515214, 56.75380575, 14.01389792, 65.71598672, 76.2885975 ,
       64.49094509, 45.16565446, 52.40365396, 66.55586151, 28.39766419,
       42.90242175, 50.37998056, 55.80818641, 90.70078142, 64.64134476,
       14.56955827, 52.44228994, 52.50261187, 35.02731689, 63.71235875,
       27.37094074, 43.978934  , 46.41300765, 43.16588475, 77.41147277,
       62.73105139, 54.06458512, 40.64562825, 83.2689234 , 69.17899502,
       64.58930812, 63.91711614, 15.90823389, 67.44717806, 77.07357463,
       55.41095706, 63.02932283, 68.8899558 , 57.27020451, 42.18293686,
       66.50380066, 44.80093079, 50.44027829, 46.42861952, 91.24783978,
       58.48723903, 59.94727568, 87.00340181, 56.0129438 , 83.77890717,
       43.94157934, 28.031974  , 88.23926126, 44.10508908, 78.02427271,
       63.37960019, 77.49419321, 41.42926913, 69.38398217, 83.00900196,
       54.36223096, 46.99929686, 83.78532216, 31.21936985, 33.38329911,
       48.44564816, 68.33937419, 70.26028173, 48.28375474, 71.57985234,
       18.80059557, 51.26550773, 51.72217944, 33.79208304, 79.42972189,
       50.70124539, 35.96138164, 55.03538946, 73.20147161, 45.21416785,
       17.14284213, 85.27857052, 58.74843588, 54.32833872, 87.6424082 ,
       47.06192156, 69.4488488 , 32.97324439, 56.53570263, 61.81223338,
       31.73738494, 52.11878318, 58.1975742 , 38.2523822 , 34.62268182,
       67.6263043 , 66.88030867, 41.11695183, 39.01754367, 50.94424291,
       92.92217161, 56.94828988, 65.03610242, 88.90767603, 65.76961358,
       23.48606266, 78.10254001, 45.03788305, 87.7142605 , 74.44754938,
       65.48346148, 50.92599326, 40.24925426, 28.90762375, 68.47770946,
       77.60717739, 34.60414157, 53.255989  , 69.09627458, 36.2852032 ,
       88.91692783, 38.35940216, 43.03683792, 25.12337484, 50.30489561,
       31.38259951, 76.70759975, 35.59157923, 43.74008534, 46.37085432,
       57.2759697 , 78.01981958, 34.56584651, 74.26808224, 55.2305234 ,
       39.76672163, 59.00103074, 80.38297671, 32.43260103, 94.75235159,
       45.95508473, 68.39019035, 30.91473834, 69.5293273 , 35.30514706,
       43.52481903, 20.47333528, 65.04533002, 55.2455404 , 23.29157853,
       73.03446472, 25.89906944, 66.01808569, 30.01479559, 39.48409279,
       76.50451362, 85.0690694 , 32.60090944, 40.00724746, 23.03799294,
       88.6106558 , 61.10424223, 48.62735723, 28.46182017, 74.78833927,
       51.57016344, 66.33935051, 61.92024407, 84.40803614, 46.2731169 ,
       31.54988647, 58.14488775, 45.25124243, 78.15423574, 70.33976951,
       73.96021808, 72.07481912, 58.76600961, 65.28897735, 33.35517205,
       64.83906155, 65.91810633, 38.28559852, 88.74444636, 63.7650452 ,
       47.07213988, 63.1480964 , 62.31523149, 60.44576571, 26.51888577,
       96.19708656, 47.68111229, 36.4777562 , 63.97332584, 72.07737585,
       68.61118521, 61.38947812, 47.83633484, 42.09098882, 30.5433196 ,
       38.31596751, 48.40539585, 25.56502956, 46.28171889, 36.37715124,
       32.25089196, 52.79707536, 73.02810466, 34.16186125, 57.06005358,
       43.34216954, 60.59201653, 20.53241253, 85.36353289, 80.83102222,
       45.38085993, 66.63983316, 30.59665586, 95.63344982, 49.31558766,
       19.67465321, 48.42137936, 86.40266628, 28.81851252, 39.44579772,
       28.40527546, 25.42962267, 66.18285064, 71.45463767, 64.01261163,
       43.5542032 , 21.8896526 , 68.84589555, 39.6275068 , 44.99541492,
       23.4483932 , 65.94237513, 62.84599743, 51.06202576, 77.27827709,
       87.47571611, 62.78916212, 28.14535402, 74.79725607, 79.68330748,
       42.34642049, 43.59573092, 50.32689827, 70.55153677, 64.96007705,
       46.50433008, 59.8364785 , 46.0830859 , 82.2942608 , 35.40825383,
       56.31754457, 39.62974873, 73.52435276, 66.35115906, 21.40167149,
       82.44593589, 30.43734529, 65.39952057, 71.97009602, 91.72015409,
       56.33704543, 18.88967607, 43.46387149, 81.31420466, 75.60394526,
       25.02083874, 36.06230141, 47.7284052 , 24.77721561, 35.9811973 ,
       32.25250829, 27.29619669, 19.91350187, 39.52976937, 64.3957905 ,
       89.01304893, 88.52795957, 39.88109238, 71.50894045, 61.92722974,
       61.25946478, 86.54094071, 69.91892118, 92.57663799, 78.99507705,
       45.5772752 , 30.87545255, 43.55067995, 78.3497106 , 68.1698453 ,
       40.19818414, 62.94211853, 87.2668406 , 19.6896702 , 55.91296444,
       96.43148209, 70.9382389 , 28.87920609, 62.74346133, 74.3026243 ,
       43.87035265, 66.39521931, 32.80336997, 52.13859884, 81.91585639,
       30.00332605, 66.36680165, 67.17253023, 63.72039007, 88.23383698,
       26.00730988, 55.67856891, 32.7098056 , 21.49426933, 71.68199259,
       58.56896874, 94.62111777, 21.46937493, 81.77150197, 51.70040654,
       55.60862354, 61.10523295, 41.91660042, 42.43935925, 69.40155589,
       76.65556311, 86.10507538, 63.99597831, 33.32837072, 69.99746855,
       68.45090813, 94.24012589, 58.15638149, 37.73379643, 61.67846703,
       25.63046686, 60.6769789 , 63.79283725, 55.09956965, 43.44468144,
       43.94126454, 37.47220373, 76.29339617, 33.70774628, 70.31072625,
       40.83656492, 54.61800354, 73.89830403, 35.26807247, 28.4551251 ,
       69.90674099, 72.48584498, 82.07550787, 62.03484457, 74.90711284,
       88.35709442, 84.00984028, 34.82358095, 41.1396043 , 61.68584854,
       40.13524863, 40.83208105, 64.46065714, 36.41422582, 37.21064176,
       31.76324586, 48.89595981, 70.7303541 , 66.82347336, 33.4477699 ,
       55.41859254, 71.88257692, 86.18555388, 51.18119517, 85.30000251,
       44.90346688, 90.21569206, 77.60655178, 66.09694787, 44.38834354,
       39.01592734, 36.04887654, 93.0489523 , 31.343618  , 33.13868526,
       65.522443  , 62.76489332, 67.7160104 , 78.99224024, 44.20183579,
       51.24472555, 48.27259601, 76.57380919, 21.65525707, 73.56650609,
       41.48675425, 70.9290113 , 86.27304878, 45.91926136, 19.63059295,
       53.52295105, 35.1182984 , 74.61523219, 68.27842665, 34.25798235,
       23.89228985, 45.2889119 , 79.10269189, 17.05949609, 59.72309848,
       68.33937419, 57.50395023, 56.55296155, 73.15548022, 21.17079331,
       83.53111097, 52.41418708, 38.76299157, 79.4054773 , 46.16521146,
       41.24656933, 30.82117398, 82.40764082, 62.78274712, 28.42670745,
       45.18067145, 53.6474898 , 72.13968575, 90.18282127, 50.44445135,
       58.09983678, 20.298017  , 41.48866117, 37.04394968, 74.03595285,
       73.31768844, 16.9553986 , 74.39712907, 68.71974046, 80.06810268,
       28.78725806, 40.28090457, 65.44996509, 44.69334015, 32.57723552,
       59.16871355, 50.28698687, 60.29442563, 42.93373115, 32.19403244,
       69.19528742, 69.84065388, 66.31124766, 46.1862476 , 85.79658562,
       27.99013147, 68.88515713, 88.05337912, 50.94580892, 80.63238923,
       49.74446732, 61.1802676 , 62.24690244, 42.15545961, 71.05226874,
       45.08230842, 18.38096772, 86.38290555, 50.42018256, 56.66946898,
       32.7033906 , 42.66064471, 43.72853076, 21.72358612, 81.7890757 ,
       35.08159546, 78.08689741, 86.11847604, 81.55692211, 58.76663522,
       46.47267977, 27.50697324, 76.0379645 , 78.85268449, 60.90087141,
       48.2345307 , 84.18578417, 41.34847982, 83.21912869, 28.97756913,
       66.94769731, 58.51565668, 74.2869817 , 80.40977804, 56.58612294,
       58.12410557, 42.362404  , 55.01015415, 90.50853922, 74.22882066,
       53.39109162, 77.83586857, 79.7810449 , 83.39797022, 43.42742251,
       27.29428977, 31.96664679, 20.43342389, 50.81485517, 58.13310341,
       55.68302205, 39.71565151, 87.67082585, 52.42028728, 87.07587972,
       53.78769536, 29.39560486, 54.22679334, 62.58156792, 84.24486141,
       62.10254802, 31.58795178, 69.18186255, 41.16259768, 84.19438616,
       24.425267  , 34.29980067, 83.18620296, 47.89702841, 60.84946037,
       71.72644869, 63.80785424, 75.25940236, 46.13069361, 33.36666579,
       83.22611436, 33.66465254, 35.7484181 , 48.11930459, 61.84515911,
       38.87798792, 43.07167057, 63.30936421, 31.4304873 , 41.54134763,
       55.01114487, 50.0720922 , 19.48016907, 35.68931665, 81.30398634,
       82.40480402, 49.09581328, 60.0778839 , 81.73224039, 19.74235665,
       68.00763708, 57.36053622, 70.58316288, 75.3046831 , 82.44085715,
       33.73715465, 90.4976953 , 72.8492324 , 73.36753809, 19.95693651,
       31.8312399 , 62.92681094, 49.95294699, 45.18893254, 48.40221351,
       74.32238502, 63.49939521, 51.59378242, 27.66662472, 75.61192165,
       88.09843009, 85.70906651, 42.90145524, 52.00764509, 53.13052037,
       36.27180254, 36.71794112, 42.12224329, 60.88486369, 71.21007413,
       35.28371507, 42.50607197, 74.42940499, 46.26133256, 74.56095361,
       94.42600803, 60.84020857, 74.76628167, 65.74343786, 35.25947048,
       88.50369077, 53.07104727, 40.15668062, 60.80216746, 64.17544545,
       47.34997006, 48.49671828, 20.01956122, 37.01876468, 55.50673725,
       55.2305234 , 44.46303265, 29.54185567, 29.15641066, 30.73428048,
       72.6266212 , 35.07807221, 73.90114084, 63.0206659 , 71.78612081,
       33.01766976, 44.16255   , 48.93715252, 42.12987877, 27.04042412,
       28.3768578 , 45.01744178, 45.47190229, 89.1072389 , 78.76068152,
       30.46477223, 63.56292559, 80.53817505, 70.70032012, 51.5832493 ,
       51.74483191, 76.25092804, 36.94084291, 41.88974878, 61.13683295,
       86.93569836, 92.24035618, 78.34167927, 59.72213196, 54.37276408,
       44.54229067, 58.91930103, 50.73150913, 35.22526343, 20.90573819,
       23.96697896, 26.05009471, 26.03155447, 59.03268105, 50.98509471,
       90.19207307, 84.9729483 , 48.33104765, 32.71488434, 82.44593589,
       37.07207673, 52.97370569, 78.83826238, 32.28254227, 76.70660903,
       48.73849532, 18.06830489, 79.50920967, 40.59416227, 77.29006143,
       51.38907997, 33.2063645 , 63.55270727, 80.56885885, 27.98950586,
       50.36334725, 82.57433291, 44.93633767, 53.01234167, 49.21620317,
       40.28507764, 82.96105924, 43.420041  , 88.39255268, 48.9361618 ,
       48.12438333, 42.77211781, 75.35035968, 48.38435971, 48.9205192 ,
       92.80243152, 73.69388165, 38.4759338 , 48.43224749, 76.00793052,
       40.0037    , 61.97991619, 80.52125114, 35.35944984, 57.74887888,
       25.51072678, 72.27986711, 48.137784  , 69.48748478, 65.4441757 ,
       86.34583097, 68.61598389, 69.08349952, 89.13982962, 87.46930112,
       75.78977246, 61.02921811, 64.74388086, 60.73381421, 75.78977246,
       58.15828841, 50.07972768, 29.24739218, 57.75336275, 85.98181794,
       51.81477729, 56.45042546, 51.4718004 , 74.05443226, 47.37838771,
       54.9172657 , 67.73679258, 68.70986305, 41.19581401, 66.79378029,
       73.7130717 , 52.52501037, 28.65886104, 65.37808858, 78.57323799,
       24.18573189, 91.17951073, 63.86854781, 66.09533154, 41.27498698,
       62.12997495, 36.50619806, 32.84357196, 80.54742686, 59.19394886,
       35.39294624, 48.65418276, 21.88900278, 31.45793844, 50.64694261,
       66.40481202, 79.6318415 , 67.75308499, 37.3400295 , 26.10919617,
       43.45873191, 38.92783757, 36.13577004, 55.61023986, 77.39259752,
       16.64625902, 59.55929814, 69.94254016, 30.12085494, 46.58929245,
       39.23345979, 39.1223217 , 37.26309845, 36.30882219, 45.31190528,
       23.66490419, 59.5883414 , 39.07826145, 31.50298941, 63.46359604,
       72.71382551, 45.90841743, 18.1066608 , 67.24310122, 51.54012945,
       76.60923672, 48.06945495, 44.98201425, 61.91447888, 70.64700806,
       33.22779649, 74.47823318, 70.60837209, 78.5333266 , 29.25125044,
       66.14742312, 66.87389368, 29.75391354, 73.31166929, 65.06798249,
       47.79929098, 39.37971061, 41.99770453, 94.19731685, 83.24050574,
       59.37404161, 74.26617532, 77.09719362, 72.56856541, 75.65407498,
       20.53593578, 57.87693499, 23.47266199, 46.66017824, 62.738092  ,
       53.15791657, 88.91692783, 45.80017698, 68.22539929, 62.20281798,
       81.0127555 , 58.43517818, 49.52123052, 56.96330687, 82.39324944,
       30.69022023, 72.815736  , 71.4255702 , 50.59485103, 81.45438601,
       57.2759697 , 75.32131642, 29.67343503, 24.08677398, 71.5370433 ,
       23.4327506 , 69.91636444, 32.54373913, 39.74628037, 58.61558573,
       70.67190247, 60.95256714, 79.84775763, 52.03767907, 54.3267727 ,
       57.90472704, 24.94229137, 54.65728933, 67.46761933, 41.7853666 ,
       34.82865969, 61.64587631, 56.25688173, 74.43479853, 49.41068731,
       40.65550566, 52.440048  , 57.67926851, 26.55085088, 41.05625826,
       34.36051845, 24.71649784, 81.15577366, 44.07920396, 36.94720297,
       67.67995726, 33.99579477, 83.25614834, 21.02834582, 57.25263078,
       53.94734684, 61.97991619, 48.67658127, 70.00672035, 55.9506339 ,
       55.09031785, 78.4643111 , 41.42066713, 72.999352  , 44.57417074,
       32.11295254, 50.31829627, 48.53123613, 53.9671625 , 25.58419541,
       62.56498491, 56.0129438 , 62.3318648 , 51.89304459, 45.46999536,
       48.86206756, 76.81774712, 30.6886039 , 56.84132485, 90.9942542 ,
       86.04438181, 55.16026322, 54.59952413, 59.81223391, 76.81359826,
       43.09979763, 50.53356258, 61.84036044, 36.33473804, 35.89143627,
       65.07439749, 35.0058849 , 71.49807231, 67.8565876 , 51.85659561,
       82.92818845, 78.77697393, 58.08966877, 70.91561064, 28.82492752,
       65.37970491, 85.38173223, 34.02006357, 84.11808072, 37.84042055,
       73.13314256, 48.54239486, 51.07641714, 63.18037232, 37.7650509 ,
       45.50925695, 72.18819914, 31.54642406, 50.95378531, 46.74642193,
       39.20086907, 47.74212066, 62.3404668 , 43.06913804, 51.19522144,
       13.97046327, 60.65046817, 43.71288816, 74.06499612, 66.19786764,
       34.83059082, 19.25022668, 26.85519179, 57.79421455, 41.36412242])

In [24]:
xtrain

array([[ 7.71199372e-01, -3.16692884e-01, -9.89389620e-01,
         8.63028306e-01,  8.43030282e-01],
       [-7.73688358e-01, -2.82016234e-02, -9.89389620e-01,
        -3.18303216e-01, -9.01330702e-01],
       [-7.73688358e-01,  4.33384393e-01, -9.89389620e-01,
        -3.18303216e-01, -5.52458505e-01],
       ...,
       [-1.24449289e-03, -7.78278901e-01,  1.01072417e+00,
        -1.49963474e+00,  1.54077468e+00],
       [-1.24449289e-03,  3.17987889e-01,  1.01072417e+00,
        -9.08968977e-01,  1.19190248e+00],
       [ 1.54364324e+00, -8.93675405e-01,  1.01072417e+00,
        -1.49963474e+00, -2.03586309e-01]], shape=(9000, 5))

In [25]:
mean_squared_error(ytest, ypred)

4.42102928630711

In [26]:
r2_score(ytest, ypred)

0.9882252677360701

In [27]:
with open("Student-Performance-LR.pkl", 'wb') as file:
    pickle.dump((lr, scaler, le), file)